In [19]:
import numpy as np
import scipy.integrate as sp
import random as rd
import math as mp
import matplotlib.pyplot as plt
import matplotlib as mpl

In [20]:
steps =  100
birds =  100
H     =    1
beta  =    0.5
ndim  =    3

init_vel_max = 18
init_vel_min = 10
init_radius = 50

In [21]:
array = np.zeros((birds * 2, ndim))

In [22]:
def functions(t, array):
    vett = np.zeros((birds * 2, ndim))
    
    for i in range(birds):
        vett[i] = array[i + birds]
    
    j = i
    somma = 0
    while i < (birds * 2):
        while j < (birds * 2):
            if i != j:
                somma += Aij(array[i - birds], array[j - birds]) * (array[j] - array[i])
            j += 1
        array[i] = somma
        i += 1

In [23]:
def Aij(xi, xj):
    return H / (pow(1 + pow(np.linalg.norm(xi - xj), 2), beta))

In [24]:
rd.seed()

for i in range (birds):
    theta_x = rd.random() * mp.pi
    phi_x = rd.random() * 2 * mp.pi
    r = rd.random() * init_radius
    
    array[i][0]= r * mp.cos(phi_x) * mp.sin(theta_x)
    array[i][1]= r * mp.sin(phi_x) * mp.sin(theta_x)
    array[i][2]= r * mp.cos(theta_x)
    
i=birds
while (i < 2*birds):
    theta_v = rd.random() * mp.pi
    phi_v = rd.random() * 2 * mp.pi
    v = rd.random() * (init_vel_max - init_vel_min) + init_vel_min
    
    array[i][0]= v * mp.cos(phi_v) * mp.sin(theta_v)
    array[i][1]= v * mp.sin(phi_v) * mp.sin(theta_v)
    array[i][2]= v * mp.cos(theta_v)
    i+=1

print (array)

[[ 1.96302127e+01  3.48722553e+01  1.20619504e+01]
 [ 5.23751539e+00  2.54691218e+00  1.89082120e+01]
 [ 2.54094239e-01  2.98387427e+00 -1.96974463e+01]
 [ 3.11953106e+01 -2.18294217e+01  9.43063899e+00]
 [-2.02752331e+01  1.21960250e+01 -1.34640596e+01]
 [-3.61093232e+01 -2.12930149e+00  8.65243504e+00]
 [ 1.16842546e+00  4.21413117e+00  5.27145484e-01]
 [ 1.69230141e+01  1.27578374e+01 -4.34131065e+01]
 [ 1.86535376e+00 -8.55109317e-01  1.10660000e+00]
 [ 2.83907779e+00 -1.61195896e-01  7.77055059e-01]
 [ 2.22067114e+00  1.49616975e+00  3.72720755e+00]
 [-4.52131082e-01  4.78353222e+00 -1.36853586e+00]
 [ 1.30136188e+01 -3.42315647e+01  2.35756845e+01]
 [-7.38851438e+00 -4.56395148e+00  3.39941529e+01]
 [-1.17624290e+01 -1.26163200e+01 -3.65778518e+01]
 [-1.02838338e+01 -1.37288891e+01 -4.71171414e+00]
 [-7.45498395e+00  1.26027712e+01 -6.59839054e+00]
 [ 3.15984987e-01  9.19149278e+00  4.45344221e+01]
 [ 3.66384640e+01 -7.48794967e+00  2.90213274e+01]
 [-1.24856578e+00 -1.56680639e+

In [26]:
f1 = open(f"vel3D birds={birds} steps={steps} b={beta}.txt", "w")
f2 = open(f"pos3D birds={birds} steps={steps} b={beta}.txt", "w")
f1.close()
f2.close()

array=array.reshape((2*birds*ndim))

solution = sp.RK45(vectorized=True, t0=0, fun=functions, y0=array, t_bound=10, max_step=0.5)
       
print(solution)